name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V

  test-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 calculator.py

  deploy-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"